### ISSUE TITLE
Listener does not emit notification event

### ISSUE THREAD

**Issue by Shura0** [jjatria/Mastodon-Client#5]
Hello

I have a code:

```
my $client = Mastodon::Client->new(
  instance        => $server,
  name            => $APP_NAME,
  client_id       => $client_id,
  access_token    => $access_token,
  coerce_entities => 1,
);
my $listener = $client->stream( 'user' );

$listener->on( update => sub {
			my ($listener, $s) = @_;
			print "UPDATE ";
			print Dumper($s);
		},
		error => sub {
			my ($error, $text)=@_;
			print "ERROR: $text\n";
		},
		notification => sub {
			my ($listener, $s) = @_;
			print "NOTIFICATION ";
			print Dumper($s);
		}
	);
$listener->start;
```

And it never displays notifications, but I'm see my notifications in Web client.

**Comment by jjatria** [comment]
I think this might be an issue with how you are subscribing to events.

The documentation for [the `on` method we inherit from Role::EventEmitter](https://metacpan.org/pod/Role::EventEmitter#on) has the following example:

``` perl
my $cb = $e->on(foo => sub {...});
```

and looking at [the implementation](https://github.com/Grinnz/Role-EventEmitter/blob/4cfc11b5a25595ad864d0f5f9f4e819daecb9678/lib/Role/EventEmitter.pm#L28) it looks like it will silently drop any other arguments.

So your code was subscribing to `update` and then doing nothing with your `error` and `notification` handlers.

If your code was changed to

``` perl
$listener->on( update       => sub { ... });
$listener->on( error        => sub { ... });
$listener->on( notification => sub { ... });
```

it should work.

Closing for now, but feel free to re-open if this is not the case.
