### ISSUE TITLE
client->post does not work. Scopes is a read-only accessor

### ISSUE THREAD

**Issue by Shura0** [jjatria/Mastodon-Client#9]
New version has a bug:
scopes is a read-only accessor at /home/shura/perl5/lib/perl5/Mastodon/Client.pm line 287.

**Comment by jjatria** [comment]
Sorry for the delayed response, and thanks for the report!

This was fixed in a2108e0d via [jjatria/Mastodon-Client!4](https://gitlab.com/jjatria/Mastodon-Client/-/merge_requests/4).
